src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Maximum_License__c</fullName>
        <label>Maximum License</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Study__c</fullName>
        <label>Type of Study</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>commercial</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment to be Serviced</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type_of_Study__c</fullName>
        <label>Type of Study</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Expire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Work_Part__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>No spare parts meet this description or name.</errorMessage>
            <filterItems>
                <field>Product2.Name</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Request__c</fullName>
        <label>Maintenance Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>maintenance_cycle__c</fullName>
        <label>maintenance cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Part</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MaintenanceRequestTest.cls
@isTest
public class MaintenanceRequestTest {
    static testmethod void testcase(){
        Account acc = new  account();
        acc.Name= 'testAccount';
        acc.Maximum_License__c =2;
        acc.Type_of_Study__c ='Academic';
        insert acc;
        
        contact con =new contact();
        con.LastName='testcon';
        con.Type_of_Study__c='Academic';
        con.AccountId=acc.id;
        insert con;
        product2 pro = new product2();
        pro.Name='demo product';
        pro.Maintenance_Cycle__c=5;
        insert pro;
        
        Vehicle__c vobj =new Vehicle__c();
        vobj.Name ='Demo1';
        insert vobj;
        
        case cobj =new case();
        cobj.Type = 'Other';
        cobj.Status = 'closed';
        cobj.Origin = 'other';
        cobj.AccountId = acc.id;
        cobj.ContactId = con.id;
        cobj.Equipment__c = pro.id;
        cobj.Vehicle__c= vobj.id;
        insert cobj;
        Work_Part__c  wr = new Work_Part__c();
        wr.Maintenance_Request__c = cobj.id;
        wr.Equipment__c = pro.Id;
        insert wr;
        test.startTest();
        cobj.Type = 'Repair';
        update cobj;
        test.stopTest();
    }
    static testmethod void testcase1(){
        product2 pro = new product2();
        pro.Name='demo product';
        pro.Maintenance_Cycle__c=5;
        insert pro;
        
        Vehicle__c vobj =new Vehicle__c();
        vobj.Name ='Demo1';
        insert vobj;
        
        case cobj =new case();
        cobj.Type = 'Other';
        cobj.Status = 'closed';
        cobj.Origin = 'other';
        cobj.Equipment__c = pro.id;
        cobj.Vehicle__c= vobj.id;
        insert cobj;
        test.startTest();
        cobj.Type = 'Repair';
        update cobj;
        test.stopTest();
    }
}