src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>DEAL-{0000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityOverRideController.cls
public class OpportunityOverRideController {
       public static Map<Id, String> recordtypemap {get;set;}
    
   @AuraEnabled        
    public static List<String> fetchRecordTypeValues(){
        List<Schema.RecordTypeInfo> recordtypes = opportunity.SObjectType.getDescribe().getRecordTypeInfos();    
        recordtypemap = new Map<Id, String>();
        for(RecordTypeInfo rt : recordtypes){
            if(rt.getName() != 'Master')
            recordtypemap.put(rt.getRecordTypeId(), rt.getName());
        } 
        system.debug('@@@######'+recordtypemap.values());
        return recordtypemap.values(); 
    }
    
   @AuraEnabled
    public static Deal__c getdefaultvalues(id dealId){
         system.debug('@@@dealId######'+dealId);
        Deal__c dealobj =[select id,name ,Account__c,Principal_Contact__c from Deal__c where id=:dealId limit 1];
        system.debug('@@@dealobj######'+dealobj);
        return dealobj;
    }
    @AuraEnabled
    public static string getrecordtypeid(string recordTypeLabel){
         system.debug('@@@recordTypeLabel######'+recordTypeLabel);
        string Id = [SELECT id from RecordType where Name =:recordTypeLabel and sObjectType='opportunity'].Id;
         system.debug('@@@Id######'+Id);
        return Id;
    }
}