src/objects/Master__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>23</length>
        <type>Text</type>
    </fields>
    <label>Master</label>
    <nameField>
        <label>Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SaveController.cls
public class SaveController {
@AuraEnabled
public static Master__C saveRecord(Master__C mas){
    upsert mas; 
    return mas; 
}
    @AuraEnabled
   public static Master__C saveRecorddetails(string name, string firstname, string email,date tdate){
    Master__C temp =new Master__C();
    temp.Name= name; 
    temp.LastName__c= firstname; 
    temp.Email__c= email; 
      temp.Due_Date__c= tdate;   
       insert temp;
       return temp;
} 
}