src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DB_Competitor__c</fullName>
        <description>This is a field that is installed by and used with the Adoption Dashboard AppExchange package. If your org already has a similar field, you can change the reports that are part of the Adoption Dashboard package to use your custom field and can delete this field.</description>
        <label>DB Competitor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Competitor A</fullName>
                </value>
                <value>
                    <fullName>Competitor B</fullName>
                </value>
                <value>
                    <fullName>Competitor C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MainCompetitors__c</fullName>
        <label>Main Competitor(s)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <label>Order Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingNumber__c</fullName>
        <label>Tracking Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Opptytabelcontroller.cls
public class Opptytabelcontroller {
 @AuraEnabled
    public static void getOpportunityAmount(String oppId,string MCompetitor){
        system.debug('opp@@@@@'+MCompetitor);
        opportunity opp=[SELECT id,DB_Competitor__c,MainCompetitors__c,OrderNumber__c,TrackingNumber__c FROM Opportunity WHERE Id=:oppId];
        //opp.DB_Competitor__c =Competitor;
        opp.MainCompetitors__c =MCompetitor;
        //opp.TrackingNumber__c =TNumber;
        //opp.OrderNumber__c =ONumber;
        update opp;
        system.debug('opp@@@@@'+opp);
    }
     @AuraEnabled
    public static opportunity getOpportunity(String oppId){
        opportunity opp=[SELECT id,DB_Competitor__c,MainCompetitors__c,OrderNumber__c,TrackingNumber__c FROM Opportunity WHERE Id=:oppId];
        
        return opp;
    }

}