src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Inventory__c</fullName>
        <label>Current Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifespan_Months__c</fullName>
        <label>Lifespan Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Warehouse_SKU__c</fullName>
        <externalId>true</externalId>
        <label>Warehouse SKU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WarehouseCalloutService.cls
public with sharing class WarehouseCalloutService {

    private static final String WAREHOUSE_URL = 'https://th-superbadge-apex.herokuapp.com/equipment';
    
    // complete this method to make the callout (using @future) to the
    // REST endpoint and update equipment on hand.
    @future(callout =true)
    public static void runWarehouseEquipmentSync(){
        httpRequest req =new httpRequest();
        req.setEndpoint(WAREHOUSE_URL);
        //req.setHeader(key, value);
        req.setMethod('GET');
        Http http =new Http();
        Httpresponse res =http.send(req);
        if(res.getStatusCode() == 200){
            List<object> equipments =(List<object>) JSON.deserializeUntyped(res.getBody());
            List<Product2> Products=new  List<Product2>();
            for(object o:equipments){
            	Map<String, Object> mapProduct = (Map<String, Object>)o;
    			Product2 product = new Product2();
                product.Name = (string)mapProduct.get('name');
                product.Cost__c = (integer)mapProduct.get('cost');
                product.Current_Inventory__c = (integer)mapProduct.get('quantity');
                product.Lifespan_Months__c = (integer)mapProduct.get('lifespan');
                product.Maintenance_Cycle__c= (integer)mapProduct.get('maintenanceperiod');
                product.Warehouse_SKU__c =(string) mapProduct.get('sku');
                product.ProductCode  =(string) mapProduct.get('_id');
                Products.add(product);
            } 
            if(Products.size()>0)
              upsert Products;  
        }
    }

}